//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitoModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRUEBA1Entities : DbContext
    {
        public PRUEBA1Entities()
            : base("name=PRUEBA1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLASEVEHICULO> CLASEVEHICULO { get; set; }
        public virtual DbSet<FACTURA> FACTURA { get; set; }
        public virtual DbSet<FACTURA_TRAMITE> FACTURA_TRAMITE { get; set; }
        public virtual DbSet<LINEA> LINEA { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<PROPIETARIO> PROPIETARIO { get; set; }
        public virtual DbSet<PROPIETARIO_VEHICULO> PROPIETARIO_VEHICULO { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPOSERVICIO> TIPOSERVICIO { get; set; }
        public virtual DbSet<TRAMITE> TRAMITE { get; set; }
        public virtual DbSet<VEHICULO> VEHICULO { get; set; }
    }
}
