//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPIETARIO_VEHICULO
    {
        public decimal ID_PROPIETARIO { get; set; }
        public decimal ID_VEHICULO { get; set; }
        public Nullable<System.DateTime> CREA_FECHA { get; set; }
    
        public virtual PROPIETARIO PROPIETARIO { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
    }
}
